 POST http://localhost:7001/appointment/generate
Content-Type: application/json

{
  "date": "2024-12-02",
  "slotsPerHour": 2
}

#### Get All Appointments
GET http://localhost:7001/appointment

#### blockieren
PATCH http://localhost:7001/appointment/674d3b06ef9705a489951948
Content-Type: application/json

{
  "status": "blocked"
}

#### unblockieren
PATCH http://localhost:7001/appointment/674d3b06ef9705a489951948
Content-Type: application/json

{
  "status": "available"
}

#### Buchen
POST http://localhost:7001/appointment/book
Content-Type: application/json

{
  "slotId": "{slotId}",
  "customerDetails": {
    "fullName": "Max Mustermann",
    "email": "max@mustermann.de",
    "phone": "+4915123456789",
    "licensePlate": "M-XX 1234",
    "notes": "Bitte pünktlich kommen"
  }
}

#### bestätigen
PATCH http://localhost:7001/appointment/674d3b06ef9705a489951948/confirm




