#### create appointment
POST http://localhost:7001/appointment/create
Content-Type: application/json

{
   "firstName": "Ghulam",
   "lastName": "Karimi",
   "email": "karimiamirhossein12@gmail.com",
   "phone": "1234567890",
   "date": "2024-12-05",
   "time": "12:00",
   "licensePlate": "1234",
   "service": "Oil Change",
   "comment": "Please change the oil",
   "hsn": "1234",
    "tsn": "abcd"
}

#### cancel appointment
POST http://localhost:7001/appointment/cancel
Content-Type: application/json

{
   "appointmentId": "674f7c4b4c5553fa8c58e3e8"
}

#### block appointment
POST http://localhost:7001/appointment/block
Content-Type: application/json

{
  "date": "2024-12-06",
  "time": "13:30"
}

#### unblock appointment
DELETE http://localhost:7001/appointment/unblock
Content-Type: application/json

{
  "appointmentId": "674f78824c1561ab57acfb63"
}

#### get all appointments
GET http://localhost:7001/appointment/all
Content-Type: application/json

