#### create Car Buy
POST http://localhost:7001/buy/create
Content-Type: application/json


{
    "carTitle": "BMW",
    "carPrice": "12000",
    "carImage": ["https://cdn.bimmertoday.de/wp-content/uploads/2021/02/2021-BMW-X5-G05-M50d-Schwarz-Shadow-Line-erweitert-Winter-Schnee-04-1024x683.jpg", "https://cdn.bimmertoday.de/wp-content/uploads/2021/02/2021-BMW-X5-G05-M50d-Schwarz-Shadow-Line-erweitert-Winter-Schnee-20-750x500.jpg","https://cdn.bimmertoday.de/wp-content/uploads/2023/08/2023-BMW-X5-M-F95-LCI-Frozen-Black-Individual-Facelift-11-750x500.jpg","https://cdn.bimmertoday.de/wp-content/uploads/2023/08/2023-BMW-X5-M-F95-LCI-Interieur-Sakhir-Orange-Schwarz-01-1024x683.jpg","https://cdn.bimmertoday.de/wp-content/uploads/2023/08/2023-BMW-X5-M-F95-LCI-Interieur-Sakhir-Orange-Schwarz-04-1024x683.jpg","https://www.autoreifenfinder.at/images/800/d/120985f4acb24124360c58898429fc6d.jpg"],
    "carCategory": "Wohnwagen",
    "fuelType": "Diesel",
    "owner": "First Owner",
    "isSold": false,
    "carDescription": "A well-maintained Audi A6 with full service history.",
    "carKilometers": "298899",
    "carColor": "Black",
    "carAirConditioning": true,
    "carSeat": "5",
    "carEuroNorm": "Euro 6",
    "damagedCar": false,
    "carNavigation": true,
    "carParkAssist": true,
    "carAccidentFree": true,
    "carFirstRegistrationDay": "2010-05-01",
    "carGearbox": "Automatic",
    "carMotor": "2.0L",
    "carHorsePower": "150",
    "carTechnicalInspection": "2024-10-01",
    "userId": "6728c1b4b847d4c2fd433414"
}

#### get all Car Buy
GET http://localhost:7001/buy/allBuys
Content-Type: application/json


####  delete Car Buy
DELETE http://localhost:7001/buy/delete/
Content-Type: application/json

{
    "carId": "672184d47fe8a67f6bf1288e",
    "userId": "6728c1b4b847d4c2fd433414"
}

#### update Car Buy
PUT http://localhost:7001/buy/update
Content-Type: application/json

{
    "carId": "6721882169a78e1207348d63",
    "userId": "6728c1b4b847d4c2fd433414",
    "carTitle": "BMW",
    "carPrice": "10000",
    "carImage": ["image1_url.jpg", "image2_url.jpg"],
    "carCategory": "Wohnwagen",
    "fuelType": "Diesel",
    "owner": "First Owner",
    "isSold": false,
    "damagedCar": false,
    "carDescription": "A well-maintained Audi A6 with full service history.",
    "carKilometers": "298899",
    "carColor": "Black",
    "carEuroNorm": "Euro 6",
    "carAirConditioning": true,
    "carSeat": "5",
    "carNavigation": true,
    "carParkAssist": true,
    "carAccidentFree": true,
    "carFirstRegistrationDay": "2010-05-01",
    "carGearbox": "Automatic",
    "carMotor": "2.0L",
    "carHorsePower": "579",
    "carTechnicalInspection": "2024-10-01"
}