#### created Offer
POST http://localhost:7001/offer/createOffer
Content-Type: application/json

{
    "title": "Reifen wechseln bei uns",
    "description": "description",
    "oldPrice":"120",
    "newPrice":"75",
    "imageUrl":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRSZNbZId4DLbjraJ5qbzEtfQF5xx1fmu4CQ&s",
    "userId": "674b6401acf7065df0f5baac"
}

#### edit Offer
PUT http://localhost:7001/offer/editOffer
Content-Type: application/json

{
    "offerId": "672a78a02ed646d3bb02e296",
    "title": "Öl wechseln bei uns",
    "description": "Profitieren Sie von unserem schnellen und zuverlässigen Ölwechsel-Service.",
    "oldPrice": "165",
    "newPrice": "130",
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRSZNbZId4DLbjraJ5qbzEtfQF5xx1fmu4CQ&s",
    "userId": "6746413a50dac6933deb044e"
}


#### delete Offer
DELETE http://localhost:7001/offer/deleteOffer
Content-Type: application/json

{
    "offerId": "674b9c1d07972446b53f80a2",
    "userId": "674b6401acf7065df0f5baac"
}

#### get all Offers
GET http://localhost:7001/offer/getOffers
Content-Type: application/json
