#### add car to rent
POST http://localhost:7001/rent/create
Content-Type: application/json

{
    "carName": "car1",
    "carImage": "image1",
    "carPrice":"100",
    "carDoors":"5",
    "carGear":"automatic",
    "carPeople":"5",
    "carAC":true,
    "userId": "670b044f9630e5a6dac49dea"
}

#### get Car Rents
GET http://localhost:7001/rent/getRents
Content-Type: application/json

#### get Car Rent by id
GET http://localhost:7001/rent/getRent/670cd0850a145fdf7824a9c3
Content-Type: application/json


#### delete Car Rent by id
DELETE http://localhost:7001/rent/deleteRentCar
Content-Type: application/json

{
  "userId": "670b044f9630e5a6dac49dea", 
  "CarId": "670cd2c2a21f2de60264fbce"
}

#### update Car Rent by id
PUT http://localhost:7001/rent/updateRentCar
Content-Type: application/json

{
  "userId": "670b044f9630e5a6dac49dea", 
  "carId": "670ce3d736933cbb3f8aa046",
  "carName": "toyota",
  "carImage": "toyota image",
  "carPrice": "500",
  "carDoors": "5",
  "carGear": "automatic",
  "carPeople": "5",
  "carAC": true
}

#### get Car Rent by user id
GET http://localhost:7001/rent/getRentByUser
Content-Type: application/json

{
  "userId": "670b044f9630e5a6dac49dea"
}

#### book 

