#### register User
POST http://localhost:7001/user/register
Content-Type: application/json

{
    "firstName":"Ghulam",
    "lastName":"Karimi",
    "email":"karimiamirhossein12@gmail.com",
    "password":"123456",
    "confirmPassword":"123456",
    "phone":"1234567" 
}

#### login User
POST http://localhost:7001/user/login
Content-Type: application/json

{
    "email":"karimiamirhossein12@gmail.com",
    "password":"123456"
}    

#### logout user
DELETE http://localhost:7001/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQ3NWI1ODVlNjllOGQ5MTU5MTdmMDEiLCJmaXJzdE5hbWUiOiJHaHVsYW0gSG9zc2VpbiIsImxhc3ROYW1lIjoiS2FyaW1pIiwiZW1haWwiOiJrYXJpbWlhbWlyaG9zc2VpbjEyQGdtYWlsLmNvbSIsInBob3RvIjoiaHR0cHM6Ly93d3cucG5ncGxheS5jb20vd3AtY29udGVudC91cGxvYWRzLzEyL1VzZXItQXZhdGFyLVByb2ZpbGUtUE5HLUZyZWUtRmlsZS1Eb3dubG9hZC5wbmciLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzMyNzMzMDk0LCJleHAiOjE3MzUzMjUwOTR9.SFX3g0VKB3J1_VVcpscgcsyM6OOkTY63j2suWf2Dfy8

 
### Refresh User Token
GET http://localhost:7001/user/refreshToken
 

#### get user profile
GET http://localhost:7001/user/allUsers
Content-Type: application/json


#### edit user profile
PUT http://localhost:7001/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzI4YzFiNGI4NDdkNGMyZmQ0MzM0MTQiLCJmaXJzdE5hbWUiOiJHaHVsYW0iLCJsYXN0TmFtZSI6IkthcmltaSIsImVtYWlsIjoia2FyaW1pYW1pcmhvc3NlaW4xMkBnbWFpbC5jb20iLCJwaG90byI6Imh0dHBzOi8vd3d3LnBuZ3BsYXkuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8xMi9Vc2VyLUF2YXRhci1Qcm9maWxlLVBORy1GcmVlLUZpbGUtRG93bmxvYWQucG5nIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzMyNTY5MDEwLCJleHAiOjE3MzI1Njk5MTB9.vvur4qdi1K6-7mZ8Axowb0X6-pChMkeh16Gub75qdd0
Content-Type: application/json

{
    "firstName":"bahar",
    "lastName":"ahmdi",
    "email":"bahar@gmail.com",
    "password":"bahar.2020",
    "confirmPassword":"bahar.2020",
    "phone":"1234567" 
}

#### delete user
DELETE http://localhost:7001/user/deleteUser/670869c8582228e388748057
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzBiMDQ0Zjk2MzBlNWE2ZGFjNDlkZWEiLCJmaXJzdE5hbWUiOiJhbWlyYWxpIiwibGFzdE5hbWUiOiJob3NzZWluaSIsImVtYWlsIjoiYW1nZ2dAZ21haWwuY29tIiwicGhvbmUiOiIxMjM0NTY3IiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzI4Nzc1NjgxLCJleHAiOjE3MzEzNjc2ODF9.yN-TfqPKGdyj5UlwZE3E_UOlbI83_WArxBLGxkSf_tU

#### change password user by logged in user
PUT http://localhost:7001/user/changePassword
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzBiMDQ0Zjk2MzBlNWE2ZGFjNDlkZWEiLCJmaXJzdE5hbWUiOiJhbWlyYWxpIiwibGFzdE5hbWUiOiJob3NzZWluaSIsImVtYWlsIjoiYW1nZ2dAZ21haWwuY29tIiwicGhvbmUiOiIxMjM0NTY3IiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzI4Nzc2ODUwLCJleHAiOjE3MzEzNjg4NTB9.gitXR8BNMU-hcKdl6BgwifaW-eeaBCLG9SyR-WuxSy0
Content-Type: application/json

{
    "password":"amir.12",
    "newPassword":"amir.123",
    "confirmPassword":"amir.123"
}

#### confirm email 
POST http://localhost:7001/user/confirmEmail
Content-Type: application/json

{
    "email":"autoservice.aundo@gmail.com"
}


#### confirm verification code 
POST http://localhost:7001/user/confirmVerificationCode
Content-Type: application/json

{
    "email":"karimiamirhossein12@gmail.com",
    "verificationCode":"766075"

}

#### Change Password With Email
PUT http://localhost:7001/user/changePasswordWithEmail
Content-Type: application/json

{
    "email": "karimiamirhossein12@gmail.com",
    "newPassword": "amir.12345",
    "confirmPassword": "amir.12345"
}

#### profile image
POST http://localhost:7001/user/uploadProfileImage








 






 







