#### register User
POST http://localhost:7001/user/register
Content-Type: application/json

{
    "firstName":"Hossein",
    "lastName":"Karimi",
    "email":"hossein12@gmail.com",
    "password":"Amir.2020",
    "confirmPassword":"Amir.2020",
    "phone":"01522364566" 
}

#### login User
POST http://localhost:7001/user/login
Content-Type: application/json

{
    "email":"hossein12@gmail.com",
    "password":"Amir.2020"
}    

#### logout user
DELETE http://localhost:7001/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzViN2RhYzQ2ZmUwYTFhYmU4YmYyODUiLCJmaXJzdE5hbWUiOiJHaHVsYW0iLCJsYXN0TmFtZSI6IkthcmltaSIsImVtYWlsIjoia2FyaW1pYW1pcmhvc3NlaW4xMkBnbWFpbC5jb20iLCJwaG9uZSI6IjEyMzQ1NjciLCJwaG90byI6Imh0dHA6Ly9sb2NhbGhvc3Q6NzAwMS9pbWFnZXMvdXNlckltYWdlcy8xNzM0MDg3NDc1MTg4LTQ3ODIyNjMxMC53ZWJwIiwiaXNBZG1pbiI6ZmFsc2UsImN1c3RvbWVyTnVtYmVyIjoiNjkwMjUxOTI2IiwiaWF0IjoxNzM0MDg4MTY4LCJleHAiOjE3MzQwODg3Njh9.DSSwQPQE3V7m1WE6wSlCPsFoWHTaM9v-plGyLpB8hpk

 
### Refresh User Token
GET http://localhost:7001/user/refreshToken
 

#### get user profile
GET http://localhost:7001/user/allUsers
Content-Type: application/json


#### edit user profile
PUT http://localhost:7001/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzViN2RhYzQ2ZmUwYTFhYmU4YmYyODUiLCJmaXJzdE5hbWUiOiJiYWhhciIsImxhc3ROYW1lIjoiYWhtZGkiLCJlbWFpbCI6ImJhaGFyQGdtYWlsLmNvbSIsInBob25lIjoiMTIzNDU2NyIsInBob3RvIjoiaHR0cDovL2xvY2FsaG9zdDo3MDAxL2ltYWdlcy91c2VySW1hZ2VzLzE3MzQwODc0NzUxODgtNDc4MjI2MzEwLndlYnAiLCJpc0FkbWluIjpmYWxzZSwiY3VzdG9tZXJOdW1iZXIiOiI2OTAyNTE5MjYiLCJpYXQiOjE3MzQwODgwNzIsImV4cCI6MTczNDA4ODY3Mn0.uFreI3izmv6ZXrLlcS-Mr5P0Hoh9aPGn5qr1S6liK2Q
Content-Type: application/json

{
    "firstName":"Ghulam",
    "lastName":"Karimi",
    "email":"karimiamirhossein12@gmail.com",
    "password":"Sara.2020",
    "confirmPassword":"Sara.2020",
    "phone":"1234567" 
}

#### delete user
DELETE http://localhost:7001/user/deleteaccount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzUyZTc3ZGI2OWM0Mjc0MDU3ZTEzYTQiLCJmaXJzdE5hbWUiOiJHaHVsYW0gSG9zc2VpbiIsImxhc3ROYW1lIjoiS2FyaW1pIiwiZW1haWwiOiJrYXJpbWlhbWlyaG9zc2VpbjEyQGdtYWlsLmNvbSIsInBob3RvIjoiaHR0cDovL2xvY2FsaG9zdDo3MDAxL2ltYWdlcy91c2VySW1hZ2VzLzE3MzM0ODY1MzIxMTItMTAwNTMwMzc3LmpwZyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MzM0ODcxMzIsImV4cCI6MTczMzQ4NzczMn0.fqqA2KSpQlK4mbFxpySEZ9AGyg1Abykbbb14qRrlw34jmQ

#### change password user by logged in user
PUT http://localhost:7001/user/changePassword
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzBiMDQ0Zjk2MzBlNWE2ZGFjNDlkZWEiLCJmaXJzdE5hbWUiOiJhbWlyYWxpIiwibGFzdE5hbWUiOiJob3NzZWluaSIsImVtYWlsIjoiYW1nZ2dAZ21haWwuY29tIiwicGhvbmUiOiIxMjM0NTY3IiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzI4Nzc2ODUwLCJleHAiOjE3MzEzNjg4NTB9.gitXR8BNMU-hcKdl6BgwifaW-eeaBCLG9SyR-WuxSy0
Content-Type: application/json

{
    "password":"amir.12",
    "newPassword":"amir.123",
    "confirmPassword":"amir.123"
}

#### confirm email 
POST http://localhost:7001/user/requestPasswordReset 
Content-Type: application/json

{
    "email":"karimiamirhossein12@gmail.com"
}


#### confirm verification code 
POST http://localhost:7001/user/confirmVerificationCode
Content-Type: application/json

{
    "email":"karimiamirhossein12@gmail.com",
    "verificationCode":"716599"

}

#### Change Password With Email
PUT http://localhost:7001/user/changePasswordWithEmail
Content-Type: application/json

{
    "email": "karimiamirhossein12@gmail.com",
    "newPassword": "amir.12345",
    "confirmPassword": "amir.12345"
}










 






 







